### ISSUE TITLE
Function calling does not work

### ISSUE THREAD

**Issue by tomoyuki28jp** [QwenLM/Qwen2-VL#142]
# Code
```
from typing import List, Union
from datetime import datetime
from qwen_agent.agents import FnCallAgent
from qwen_agent.gui import WebUI
from qwen_agent.tools.base import BaseToolWithFileAccess, register_tool

@register_tool("get_date")
class GetDate(BaseToolWithFileAccess):
    description = "call this tool to get the current date"
    parameters = [
        {
            "name": "lang",
            "type": "string",
            "description": "one of ['en', 'zh'], default is en",
            "required": False
        },
    ]

    def call(self, params: Union[str, dict], files: List[str] = None, **kwargs) -> str:
        super().call(params=params, files=files)
        params = self._verify_json_format_args(params)
        lang = "zh" if "zh" in params["lang"] else "en"
        now = datetime.now()
        result = now.strftime("%Y-%m-%d %H:%M:%S") + "\n"
        weekday = now.weekday()
        if lang == "zh":
            days_chinese = ["一", "二", "三", "四", "五", "六", "日"]
            result += "今天是星期" + days_chinese[weekday]
        else:
            days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
            result += "Today is " + days[weekday]
        return result


def init_agent_service():
    llm_cfg_vl = {
        # Using Qwen2-VL deployed at any openai-compatible service such as vLLM:
        "model_type": "qwenvl_oai",
        "model": "Qwen2-VL-7B-Instruct",
        "model_server": "http://localhost:8000/v1",  # api_base
        "api_key": 'EMPTY",
    }
    tools = [
        "get_date",
        "code_interpreter",
    ]  # code_interpreter is a built-in tool in Qwen-Agent
    bot = FnCallAgent(
        llm=llm_cfg_vl,
        name="Qwen2-VL",
        description="function calling",
        function_list=tools,
    )
    return bot

def app_gui():
    # Define the agent
    bot = init_agent_service()
    WebUI(bot).run()

# Launch gradio app
app_gui()
```

# Client Side Error
```
To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 4.21.0, however version 4.29.0 is available, please upgrade.
--------
Traceback (most recent call last):
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/qwen_agent/llm/oai.py", line 80, in _chat_stream
    response = self._chat_complete_create(model=self.model, messages=messages, stream=True, **generate_cfg)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/qwen_agent/llm/oai.py", line 66, in _chat_complete_create
    return client.chat.completions.create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 668, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/openai/_base_client.py", line 1260, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/openai/_base_client.py", line 937, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/openai/_base_client.py", line 1041, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': "1 validation error for ValidatorIterator\n0.type\n  Field required [type=missing, input_value={'text': 'You are a helpful assistant.'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.9/v/missing", 'type': 'BadRequestError', 'param': None, 'code': 400}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/gradio/route_utils.py", line 253, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/gradio/blocks.py", line 1695, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/gradio/blocks.py", line 1247, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/gradio/utils.py", line 516, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/gradio/utils.py", line 509, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/gradio/utils.py", line 492, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/gradio/utils.py", line 675, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/qwen_agent/gui/web_ui.py", line 225, in agent_run
    for responses in agent_runner.run(_history, **self.run_kwargs):
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/qwen_agent/agent.py", line 94, in run
    for rsp in self._run(messages=new_messages, **kwargs):
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/qwen_agent/agents/fncall_agent.py", line 56, in _run
    for output in output_stream:
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/qwen_agent/llm/base.py", line 274, in _convert_messages_iterator_to_target_type
    for messages in messages_iter:
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/qwen_agent/llm/base.py", line 254, in _postprocess_messages_iterator
    for pre_msg in messages:
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/qwen_agent/llm/base.py", line 430, in retry_model_service_iterator
    num_retries, delay = _raise_or_delay(e, num_retries, delay, max_retries)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/qwen_agent/llm/base.py", line 444, in _raise_or_delay
    raise e
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/qwen_agent/llm/base.py", line 425, in retry_model_service_iterator
    for rsp in it_fn():
  File "/Users/tomo/.pyenv/versions/3.12.4/lib/python3.12/site-packages/qwen_agent/llm/oai.py", line 92, in _chat_stream
    raise ModelServiceError(exception=ex)
qwen_agent.llm.base.ModelServiceError: Error code: 400 - {'object': 'error', 'message': "1 validation error for ValidatorIterator\n0.type\n  Field required [type=missing, input_value={'text': 'You are a helpful assistant.'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.9/v/missing", 'type': 'BadRequestError', 'param': None, 'code': 400}
```

# vLLM Error Log
```
python -m vllm.entrypoints.openai.api_server --served-model-name Qwen2-VL-7B-Instruct --model Qwen/Qwen2-VL-7B-Instruct --max-model-len 2048

ERROR 09-07 08:26:00 serving_chat.py:134] Error in applying chat template from request: 1 validation error for ValidatorIterator
ERROR 09-07 08:26:00 serving_chat.py:134] 0.type
ERROR 09-07 08:26:00 serving_chat.py:134]   Field required [type=missing, input_value={'text': 'You are a helpful assistant.'}, input_type=dict]
ERROR 09-07 08:26:00 serving_chat.py:134]     For further information visit https://errors.pydantic.dev/2.9/v/missing
INFO:     103.5.140.152:62122 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
```

# Ref
https://github.com/QwenLM/Qwen-Agent/issues/334

**Comment by tomoyuki28jp** [comment]
`pip install "qwen-agent>=0.0.9"` solved the problem.
