### ISSUE TITLE
通过vllm调用qwen2-vl-7b时出错

### ISSUE THREAD

**Issue by nulinuli** [QwenLM/Qwen2-VL#150]
您好，我通过源码安装您的vllm项目，拉取的是vllm-add_qwen2_vl_new分支，安装了requirements-build.txt，requirements-cuda.txt等环境，然后运行代码pip install -e .,在执行时报如下错误
  × Building editable for vllm (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [130 lines of output]
      /tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      running editable_wheel
      creating /tmp/pip-wheel-3qmciq9_/.tmp-_zrnszke/vllm.egg-info
      writing /tmp/pip-wheel-3qmciq9_/.tmp-_zrnszke/vllm.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-wheel-3qmciq9_/.tmp-_zrnszke/vllm.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-wheel-3qmciq9_/.tmp-_zrnszke/vllm.egg-info/entry_points.txt
      writing requirements to /tmp/pip-wheel-3qmciq9_/.tmp-_zrnszke/vllm.egg-info/requires.txt
      writing top-level names to /tmp/pip-wheel-3qmciq9_/.tmp-_zrnszke/vllm.egg-info/top_level.txt
      writing manifest file '/tmp/pip-wheel-3qmciq9_/.tmp-_zrnszke/vllm.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-wheel-3qmciq9_/.tmp-_zrnszke/vllm.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-wheel-3qmciq9_/.tmp-_zrnszke/vllm.egg-info/SOURCES.txt'
      creating '/tmp/pip-wheel-3qmciq9_/.tmp-_zrnszke/vllm-0.6.0+cu118.dist-info'
      creating /tmp/pip-wheel-3qmciq9_/.tmp-_zrnszke/vllm-0.6.0+cu118.dist-info/WHEEL
      running build_py
      running build_ext
      -- The CXX compiler identification is unknown
      CMake Error at CMakeLists.txt:3 (project):
        No CMAKE_CXX_COMPILER could be found.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
        to the compiler, or to the compiler name if it is in the PATH.
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 138, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 341, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 264, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 291, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 98, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "<string>", line 226, in build_extensions
        File "<string>", line 208, in configure
        File "/data/env/miniconda3/envs/qwenapi/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/home/wwh/qwen/vllm', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/tmp3_u6v4_w.build-lib/vllm', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=/tmp/tmphs9hpu0c.build-temp', '-DVLLM_TARGET_DEVICE=cuda', '-DVLLM_PYTHON_EXECUTABLE=/data/env/miniconda3/envs/qwenapi/bin/python', '-DVLLM_PYTHON_PATH=/data/env/miniconda3/envs/qwenapi/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process:/tmp/pip-build-env-azpihvrh/site:/data/env/miniconda3/envs/qwenapi/lib/python310.zip:/data/env/miniconda3/envs/qwenapi/lib/python3.10:/data/env/miniconda3/envs/qwenapi/lib/python3.10/lib-dynload:/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages:/tmp/pip-build-env-azpihvrh/normal/lib/python3.10/site-packages:/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/_vendor', '-DNVCC_THREADS=1', '-DCMAKE_JOB_POOL_COMPILE:STRING=compile', '-DCMAKE_JOB_POOLS:STRING=compile=128']' returned non-zero exit status 1.
      /tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py:973: _DebuggingTips: Problem in editable installation.
      !!
      
              ********************************************************************************
              An error happened while installing `vllm` in editable mode.
      
              The following steps are recommended to help debug this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
      
      !!
        cmd_obj.run()
      Traceback (most recent call last):
        File "/data/env/miniconda3/envs/qwenapi/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/env/miniconda3/envs/qwenapi/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data/env/miniconda3/envs/qwenapi/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 273, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 459, in build_editable
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 475, in <module>
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 138, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 341, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 264, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 291, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 98, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "<string>", line 226, in build_extensions
        File "<string>", line 208, in configure
        File "/data/env/miniconda3/envs/qwenapi/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/home/wwh/qwen/vllm', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/tmp3_u6v4_w.build-lib/vllm', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=/tmp/tmphs9hpu0c.build-temp', '-DVLLM_TARGET_DEVICE=cuda', '-DVLLM_PYTHON_EXECUTABLE=/data/env/miniconda3/envs/qwenapi/bin/python', '-DVLLM_PYTHON_PATH=/data/env/miniconda3/envs/qwenapi/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process:/tmp/pip-build-env-azpihvrh/site:/data/env/miniconda3/envs/qwenapi/lib/python310.zip:/data/env/miniconda3/envs/qwenapi/lib/python3.10:/data/env/miniconda3/envs/qwenapi/lib/python3.10/lib-dynload:/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages:/tmp/pip-build-env-azpihvrh/normal/lib/python3.10/site-packages:/tmp/pip-build-env-azpihvrh/overlay/lib/python3.10/site-packages/setuptools/_vendor', '-DNVCC_THREADS=1', '-DCMAKE_JOB_POOL_COMPILE:STRING=compile', '-DCMAKE_JOB_POOLS:STRING=compile=128']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for vllm
Failed to build vllm
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (vllm)
要怎么解决呢，麻烦您了！

**Comment by nulinuli** [comment]
硬件 A800
操作系统ubuntu22.04
环境python=3.10

**Comment by h66840** [comment]
蹲一手，我和你一样的error

**Comment by fyabc** [comment]
您好，请先检查下环境中的C++ compiler是否已正确安装，可参考[此处](https://stackoverflow.com/questions/54209495/cmake-no-cmake-cxx-compiler-could-be-found)。

**Comment by nulinuli** [comment]
> 您好，请先检查下环境中的C++ compiler是否已正确安装，可参考[此处](https://stackoverflow.com/questions/54209495/cmake-no-cmake-cxx-compiler-could-be-found)。

您好，我昨天解决了这个问题，我不知道是那个命令起作用了，一个命令时vllm官方的
export CUDA_HOME=/usr/local/cuda
export PATH="${CUDA_HOME}/bin:$PATH"
另一个命令是sudo apt-get install g++

**Comment by nulinuli** [comment]
> 蹲一手，我和你一样的error

我已解决，供您参考

**Comment by paralym** [comment]
请问有试过文档里给的pip install . --index-url https://download.pytorch.org/whl/${CUDA_VERSION}安装吗，我这边会报错cmake，ninja等版本匹配不到，比如No matching distribution found for cmake>=3.26

**Comment by nulinuli** [comment]
> 请问有试过文档里给的`pip install . --index-url https://download.pytorch.org/whl/${CUDA_VERSION}` 安装吗，我这边会报错cmake，ninja等版本匹配不到，比如No matching distribution found for cmake>=3.26

你没安装依赖吧，项目里面有requirements需要先安装的

**Comment by paralym** [comment]
> > 请问有试过文档里给的`pip install . --index-url https://download.pytorch.org/whl/${CUDA_VERSION}` 安装吗，我这边会报错cmake，ninja等版本匹配不到，比如No matching distribution found for cmake>=3.26
> 
> 你没安装依赖吧，项目里面有requirements需要先安装的

谢谢，我装完依赖并且清空existing builds之后装成功了

**Comment by KLL535** [comment]
> > 您好，请先检查下环境中的C++ compiler是否已正确安装，可参考[此处](https://stackoverflow.com/questions/54209495/cmake-no-cmake-cxx-compiler-could-be-found)。
> 
> 您好，我昨天解决了这个问题，我不知道是那个命令起作用了，一个命令时vllm官方的 export CUDA_HOME=/usr/local/cuda export PATH="${CUDA_HOME}/bin:$PATH" 另一个命令是sudo apt-get install g++

I am in Windows 10.
I don't have such paths. and so far no one has demanded
installation of something additional for cuda, the same stable diffusion FORGE works perfectly without it. There the developer generally took care of everything to be installed with one button and there was no need to sit for days looking for solutions to 1000 problems.
