### ISSUE TITLE
ImportError: cannot import name 'Qwen2VLForConditionalGeneration' from 'transformers'

### ISSUE THREAD

**Issue by Haseeeb21** [QwenLM/Qwen2-VL#156]
Cannot import this from the library,

optimum-1.21.4
transformers-4.43.4

how to fix this issue the code i am running is from the quick start documentation of `Qwen/Qwen2-VL-2B-Instruct-GPTQ-Int4`

code:
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info

model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-2B-Instruct-GPTQ-Int4", torch_dtype="auto", device_map="auto"
)

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg",
            },
            {"type": "text", "text": "Describe this image."},
        ],
    }
]

text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)
image_inputs, video_inputs = process_vision_info(messages)
inputs = processor(
    text=[text],
    images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
)
inputs = inputs.to("cuda")

generated_ids = model.generate(**inputs, max_new_tokens=128)
generated_ids_trimmed = [
    out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
]
output_text = processor.batch_decode(
    generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
)
print(output_text)

**Comment by fyabc** [comment]
@Haseeeb21 Hi, you need to install the correct version of transformers via `pip install git+https://github.com/huggingface/transformers@21fac7abba2a37fae86106f87fcf9974fd1e3830`. Check [here](https://github.com/QwenLM/Qwen2-VL?tab=readme-ov-file#quickstart) for more details.

**Comment by mahendran-narayanan** [comment]
@Haseeeb21 Installing the supported version of transformers will solve the issue
Version: 4.45.0.dev0
Installation:
`!pip install git+https://github.com/huggingface/transformers@21fac7abba2a37fae86106f87fcf9974fd1e3830 accelerate`

Currently supported models are
```
from .models.qwen2 import (
    Qwen2ForCausalLM,
    Qwen2ForSequenceClassification,
    Qwen2ForTokenClassification,
    Qwen2Model,
    Qwen2PreTrainedModel,
)
from .models.qwen2_moe import (
    Qwen2MoeForCausalLM,
    Qwen2MoeForSequenceClassification,
    Qwen2MoeForTokenClassification,
    Qwen2MoeModel,
    Qwen2MoePreTrainedModel,
)
```

**Comment by mahendran-narayanan** [comment]
Only these are supported methods . For Qwen2VLForConditionalGeneration follow this [Link](https://github.com/QwenLM/Qwen2-VL?tab=readme-ov-file#using---transformers-to-chat)

仅这些是受支持的型号
关注这个网站  https://github.com/QwenLM/Qwen2-VL?tab=readme-ov-file#using---transformers-to-chat
```
from .models.qwen2 import (
    Qwen2ForCausalLM,
    Qwen2ForSequenceClassification,
    Qwen2ForTokenClassification,
    Qwen2Model,
    Qwen2PreTrainedModel,
)
from .models.qwen2_moe import (
    Qwen2MoeForCausalLM,
    Qwen2MoeForSequenceClassification,
    Qwen2MoeForTokenClassification,
    Qwen2MoeModel,
    Qwen2MoePreTrainedModel,
)
```

**Comment by KLL535** [comment]
> `pip list | grep "transformers"` 得到： sentence-transformers 3.0.1 transformers 4.45.0.dev0
> 
> ## 进入python：
> ![image](https://private-user-images.githubusercontent.com/53348063/376193520-72e9da7b-4215-48e4-8aad-cebb725f71e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0OTAxNTYsIm5iZiI6MTczNTQ4OTg1NiwicGF0aCI6Ii81MzM0ODA2My8zNzYxOTM1MjAtNzJlOWRhN2ItNDIxNS00OGU0LThhYWQtY2ViYjcyNWY3MWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDE2MzA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxODg1NGMzZWQwZjNjZGI2NGRmYzZkMGRmM2ViZGJhYTIyZGQ4MjQwOGU3ODI3NzhjMjExNDNmZGNiYTczNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Sm--MsnQOSvRDzWJesdIZVKPWoWj8HXzUXFR-XNA0SY)
> 另外我也尝试过其他的解决方式： pip uninstall transformers pip install git+https://github.com/huggingface/transformers 或者 pip install git+https://github.com/huggingface/transformers@21fac7abba2a37fae86106f87fcf9974fd1e3830 accelerate这个版本 但是仍然没有解决，请问我下一步该如何做？谢谢
> 
> @mahendran-narayanan @ShuaiBai623

Not work!

(venv) C:\python2\qwen2>pip install git+https://github.com/huggingface/transformers
Collecting git+https://github.com/huggingface/transformers
  Cloning https://github.com/huggingface/transformers to c:\users\any\appdata\local\temp\pip-req-build-td58j3oa
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers 'C:\Users\AnY\AppData\Local\Temp\pip-req-build-td58j3oa'
  Resolved https://github.com/huggingface/transformers to commit 5cabc75b4bdb2e67935f7195f901afd150746eb3
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "C:\python2\python\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\python2\python\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\python2\python\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\python2\python\lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "C:\python2\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "C:\python2\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 545, in collect_root_requirements
    reqs = list(
  File "C:\python2\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 501, in _make_requirements_from_install_req
    cand = self._make_base_candidate_from_link(
  File "C:\python2\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 233, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\python2\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in __init__
    super().__init__(
  File "C:\python2\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 159, in __init__
    self.dist = self._prepare()
  File "C:\python2\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 236, in _prepare
    dist = self._prepare_distribution()
  File "C:\python2\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 315, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\python2\python\lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\python2\python\lib\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "C:\python2\python\lib\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\python2\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "C:\python2\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "C:\python2\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "C:\python2\python\lib\site-packages\pip\_internal\utils\misc.py", line 701, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "C:\python2\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "C:\python2\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "C:\python2\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\AnY\AppData\Local\Temp\pip-build-env-4v7kn18b\overlay\Lib\site-packages\setuptools\__init__.py", line 27, in <module>
    from .dist import Distribution
  File "C:\Users\AnY\AppData\Local\Temp\pip-build-env-4v7kn18b\overlay\Lib\site-packages\setuptools\dist.py", line 19, in <module>
    from . import (
  File "C:\Users\AnY\AppData\Local\Temp\pip-build-env-4v7kn18b\overlay\Lib\site-packages\setuptools\_entry_points.py", line 6, in <module>
    from jaraco.text import yield_lines
  File "C:\Users\AnY\AppData\Local\Temp\pip-build-env-4v7kn18b\overlay\Lib\site-packages\setuptools\_vendor\jaraco\text\__init__.py", line 12, in <module>
    from jaraco.context import ExceptionTrap
  File "C:\Users\AnY\AppData\Local\Temp\pip-build-env-4v7kn18b\overlay\Lib\site-packages\setuptools\_vendor\jaraco\context.py", line 11, in <module>
    import urllib.request
  File "urllib\request.py", line 88, in <module>
  File "http\client.py", line 71, in <module>
  File "email\parser.py", line 12, in <module>
  File "email\feedparser.py", line 27, in <module>
  File "email\_policybase.py", line 9, in <module>
  File "email\utils.py", line 29, in <module>
  File "socket.py", line 51, in <module>
ModuleNotFoundError: No module named '_socket'

**Comment by KLL535** [comment]
You can write a command to do everything manually, download archives and files from the site with a browser, for example, and then follow the steps.
When downloading manually, everything works for me. But with this incomprehensible command, it doesn't. Why are git and python mixed here? What is this incredible number after @ and why is it needed?
**pip install git+https://github.com/huggingface/transformers@21fac7abba2a37fae86106f87fcf9974fd1e3830**

(venv) C:\python2\qwen2>pip install git+https://github.com/huggingface/transformers@21fac7abba2a37fae86106f87fcf9974fd1e3830
Collecting git+https://github.com/huggingface/transformers@21fac7abba2a37fae86106f87fcf9974fd1e3830
  Cloning https://github.com/huggingface/transformers (to revision 21fac7abba2a37fae86106f87fcf9974fd1e3830) to c:\users\any\appdata\local\temp\pip-req-build-0zdozhfu
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers 'C:\Users\AnY\AppData\Local\Temp\pip-req-build-0zdozhfu'
  error: 1105 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  fatal: early EOF
  fatal: fetch-pack: invalid index-pack output
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/huggingface/transformers 'C:\Users\AnY\AppData\Local\Temp\pip-req-build-0zdozhfu' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/huggingface/transformers 'C:\Users\AnY\AppData\Local\Temp\pip-req-build-0zdozhfu' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
