### ISSUE TITLE
AttributeError: 'Qwen2VLForConditionalGeneration' object has no attribute 'quantize'. Did you mean: 'dequantize'?

### ISSUE THREAD

**Issue by CachCheng** [QwenLM/Qwen2-VL#208]
[INFO:swift] Qwen2VLForConditionalGeneration: 8291.3756M Params (0.0000M Trainable [0.0000%]), 234.8828M Buffers.
[INFO:swift] system: You are a helpful assistant.
[INFO:swift] Quantization dataset: ['ms-bench']
[INFO:swift] Start quantizing the model...
Traceback (most recent call last):
  File "/meta/cash/llm/swift/swift/cli/export.py", line 5, in <module>
    export_main()
  File "/meta/cash/llm/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/meta/cash/llm/swift/swift/llm/export.py", line 252, in llm_export
    awq_model_quantize(model, template.tokenizer, args.quant_batch_size)
  File "/meta/cash/llm/swift/swift/llm/export.py", line 138, in awq_model_quantize
    awq_model.quantize(tokenizer, quant_config=quant_config, n_parallel_calib_samples=batch_size)
  File "/home/ahs/anaconda3/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Qwen2VLForConditionalGeneration' object has no attribute 'quantize'. Did you mean: 'dequantize'?

**Comment by kq-chen** [comment]
Hi, please kindly report this to swift.

**Comment by SabrinaZhuangxx** [comment]
I have the same problem, did you find a solution?
