### ISSUE TITLE
When using `beam_search` decoding with multiple video inputs, there is an error in the rope index calculation "get_rope_index()"

### ISSUE THREAD

**Issue by taintaintainu** [QwenLM/Qwen2-VL#210]
**Description:**
When using `beam_search` decoding with multiple video inputs, there is an error in the rope index calculation "get_rope_index()". 

**Error Traceback:**
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "qwen2vl/eval/eval_model_rtl.py", line 192, in eval_model
    generated_ids = model.generate(**inputs, max_new_tokens=256, output_attentions=False, num_beams=2, do_sample=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/qwen2vl/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/qwen2vl/lib/python3.12/site-packages/transformers/generation/utils.py", line 2046, in generate
    result = self._beam_search(
             ^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/qwen2vl/lib/python3.12/site-packages/transformers/generation/utils.py", line 3169, in _beam_search
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/qwen2vl/lib/python3.12/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1676, in prepare_inputs_for_generation
    position_ids, rope_deltas = self.get_rope_index(
                                ^^^^^^^^^^^^^^^^^^^^
  File "miniconda3/envs/qwen2vl/lib/python3.12/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1480, in get_rope_index
    position_ids[..., i, attention_mask[i] == 1] = llm_positions.to(position_ids.device)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape mismatch: value tensor of shape [3, 24351] cannot be broadcast to indexing result of shape [3, 23737]
```

**Steps to Reproduce:**
1. Inference the model with multiple video inputs. And each video has different length.
2. Use `beam_search` decoding with the parameters:
   - `max_new_tokens=256`
   - `num_beams=2`
   - `do_sample=False`
3. Execute the model generation.

I guess this is due to the `beam_search` [preparation function ](https://github.com/huggingface/transformers/blob/ce62a41880b5b70a304d068eb58f55894a5a7af8/src/transformers/generation/utils.py#L582)interleaving tensors across the 0th dimension (assuming it's the batch),  whereas in the case of `video_grid_thw`, the 0th dimension represents `num_video`, not the batch size. This causes misalignment of vision thw information when calculating `llm_position`. So maybe this problem also happen when doing multi image beam search decoding inference?

**Comment by henry123-boy** [comment]
Is there any update for fixing this problem?

**Comment by Lennox-Dai** [comment]
same question

**Comment by SteinsHead** [comment]
same to me
