### ISSUE TITLE
The demo code provided by read.md runs incorrectly

### ISSUE THREAD

**Issue by WilliamRocketRen** [QwenLM/Qwen2-VL#239]
When I use the demo provided by read.md to run to output_ids = model.generate(**inputs, max_new_tokens=128), an error RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument mask in method wrapper_CUDA__masked_scatter_) appears.  My devlepment environment is as follows:
cuda:11.8
pytorch:2.1.0&2.4.1
transformers:4.45.0.dev0
accelerate:0.34.2
hardware environment: H800 80G
<img width="1587" alt="error" src="https://github.com/user-attachments/assets/346e157f-110e-4016-b9a8-b73d85e99fa0">

**Comment by WilliamRocketRen** [comment]
CUDA_AVIBLE_DEVICES=0,1,2,3,5,6,7

**Comment by xinzaifeixiang1992** [comment]
我也遇到了相同的问题，在执行官方的项目的readme.md的本地部署进行图片测试时，就报错了：
 CUDA_VISIBLE_DEVICES=4,5,6,7 python3 qwen2-vl-72b_local_image_test.py
INFO 09-22 22:29:41 llm_engine.py:223] Initializing an LLM engine (v0.6.1.post2) with config: model='/data/llms/qwen/Qwen2-VL-72B-Instruct', speculative_config=None, tokenizer='/data/llms/qwen/Qwen2-VL-72B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/data/llms/qwen/Qwen2-VL-72B-Instruct, use_v2_block_manager=False, num_scheduler_steps=1, enable_prefix_caching=False, use_async_output_proc=True)
INFO 09-22 22:29:41 model_runner.py:997] Starting to load model /data/llms/qwen/Qwen2-VL-72B-Instruct...
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/zhuq/mlm_api/qwen-vl/qwen2-vl-72b_local_image_test.py", line 12, in <module>
[rank0]:     llm = LLM(
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 178, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 550, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 317, in __init__
[rank0]:     self.model_executor = executor_class(
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 47, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 40, in _init_executor
[rank0]:     self.driver_worker.load_model()
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/worker/worker.py", line 183, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 999, in load_model
[rank0]:     self.model = get_model(model_config=self.model_config,
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py", line 19, in get_model
[rank0]:     return loader.load_model(model_config=model_config,
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 358, in load_model
[rank0]:     model = _initialize_model(model_config, self.load_config,
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 172, in _initialize_model
[rank0]:     return build_model(
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 157, in build_model
[rank0]:     return model_class(config=hf_config,
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/model_executor/models/qwen2_vl.py", line 860, in __init__
[rank0]:     self.model = Qwen2Model(config, cache_config, quant_config)
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 243, in __init__
[rank0]:     self.start_layer, self.end_layer, self.layers = make_layers(
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 248, in make_layers
[rank0]:     [PPMissingLayer() for _ in range(start_layer)] + [
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 249, in <listcomp>
[rank0]:     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 245, in <lambda>
[rank0]:     lambda prefix: Qwen2DecoderLayer(config=config,
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 184, in __init__
[rank0]:     self.mlp = Qwen2MLP(
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 69, in __init__
[rank0]:     self.down_proj = RowParallelLinear(intermediate_size,
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 975, in __init__
[rank0]:     self.quant_method.create_weights(
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 122, in create_weights
[rank0]:     weight = Parameter(torch.empty(sum(output_partition_sizes),
[rank0]:   File "/data/anaconda3/envs/qwen-vl/lib/python3.10/site-packages/torch/utils/_device.py", line 79, in __torch_function__
[rank0]:     return func(*args, **kwargs)
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 462.00 MiB. GPU 0 has a total capacity of 44.52 GiB of which 28.94 MiB is free. Including non-PyTorch memory, this process has 44.49 GiB memory in use. Of the allocated memory 44.05 GiB is allocated by PyTorch, and 116.84 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by WilliamRocketRen** [comment]
Maybe your GPU doesn't have enough memory. Do you change any devices?

**Comment by kkiskkk** [comment]
> CUDA_AVIBLE_DEVICES=0,1,2,3,5,6,7

This doesn't work

**Comment by V-yw** [comment]
@xinzaifeixiang1992 兄弟解决了吗,和你一样的问题.要加什么参数吗

**Comment by WilliamRocketRen** [comment]
It works well with four GPU. You can use this code:
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '1,2,3,4'

**Comment by WilliamRocketRen** [comment]
> > CUDA_AVIBLE_DEVICES=0,1,2,3,5,6,7
> 
> This doesn't work
It works well with four GPU. You can use this code:
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '1,2,3,4'

**Comment by kq-chen** [comment]
@WilliamRocketRen could you please check the device of each parameter? add some code like this before `model.generate`, and share the results with me.
```python
for n, p in model.named_parameters():
    print(n, p.device)
```

**Comment by WilliamRocketRen** [comment]
Model device map: {'visual': 0, 'model.embed_tokens': 0, 'model.layers.0': 1, 'model.layers.1': 1, 'model.layers.2': 1, 'model.layers.3': 1, 'model.layers.4': 1, 'model.layers.5': 1, 'model.layers.6': 1, 'model.layers.7': 1, 'model.layers.8': 2, 'model.layers.9': 2, 'model.layers.10': 2, 'model.layers.11': 2, 'model.layers.12': 2, 'model.layers.13': 2, 'model.layers.14': 2, 'model.layers.15': 2, 'model.layers.16': 3, 'model.layers.17': 3, 'model.layers.18': 3, 'model.layers.19': 3, 'model.layers.20': 3, 'model.layers.21': 3, 'model.layers.22': 3, 'model.layers.23': 3, 'model.layers.24': 4, 'model.layers.25': 4, 'model.layers.26': 4, 'model.layers.27': 4, 'model.norm': 4, 'model.rotary_emb': 4, 'lm_head': 4}
Embedding layer is on device: cuda:0

**Comment by WilliamRocketRen** [comment]
Model device map: {'visual': 0, 'model.embed_tokens': 1, 'model.layers.0': 1, 'model.layers.1': 1, 'model.layers.2': 1, 'model.layers.3': 1, 'model.layers.4': 2, 'model.layers.5': 2, 'model.layers.6': 2, 'model.layers.7': 2, 'model.layers.8': 2, 'model.layers.9': 2, 'model.layers.10': 2, 'model.layers.11': 3, 'model.layers.12': 3, 'model.layers.13': 3, 'model.layers.14': 3, 'model.layers.15': 3, 'model.layers.16': 3, 'model.layers.17': 3, 'model.layers.18': 4, 'model.layers.19': 4, 'model.layers.20': 4, 'model.layers.21': 4, 'model.layers.22': 4, 'model.layers.23': 4, 'model.layers.24': 4, 'model.layers.25': 5, 'model.layers.26': 5, 'model.layers.27': 5, 'model.norm': 5, 'model.rotary_emb': 5, 'lm_head': 5}
Embedding layer is on device: cuda:1

**Comment by hhhhpaaa** [comment]
This may be a problem with `transformers`. I executed `pip install git+https://github.com/huggingface/transformers@21fac7abba2a37fae86106f87fcf9974fd1e3830` to solve this problem. I hope this method works for you as well
