### ISSUE TITLE
CUDA out of memory for Qwen2-VL-7B-Instruct-GPTQ-Int8 on RTX3090 24G

### ISSUE THREAD

**Issue by shaojun** [QwenLM/Qwen2-VL#297]
hi,    
I basically followed: https://www.modelscope.cn/models/Qwen/Qwen2-VL-7B-Instruct-GPTQ-Int8    
and thought the `24G` gpu memory would be enough for the model:    
![image](https://github.com/user-attachments/assets/947cfecc-73a8-4c19-ad42-c77c9c1becb1)

but got error when trying to run the `python` script, the error was shown:
```
orch.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.10 GiB. GPU 0 has a total capacity of 23.69 GiB of which 5.83 GiB is free. Including non-PyTorch memory, this process has 17.62 GiB memory in use. Of the allocated memory 17.05 GiB is allocated by PyTorch, and 274.50 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
this is my `nvidia-smi`:
```
nvidia-smi
Sun Sep 29 16:59:59 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:01:00.0  On |                  N/A |
| 30%   32C    P8              30W / 350W |    239MiB / 24576MiB |     14%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1530      G   /usr/lib/xorg/Xorg                           35MiB |
|    0   N/A  N/A      3742      G   /usr/lib/xorg/Xorg                           98MiB |
|    0   N/A  N/A      4067      G   /usr/bin/gnome-shell                         80MiB |
+---------------------------------------------------------------------------------------+
```

thanks.

**Comment by kq-chen** [comment]
`flash-attn` is needed to reproduce the GPU Memory

**Comment by shaojun** [comment]
@kq-chen thanks.

But i noticed in `readme`:
```
FlashAttention-2 can only be used when a model is loaded in torch.float16 or torch.bfloat16.
```
What does it mean?using flash attention would disable loading quantization models?

**Comment by kq-chen** [comment]
sorry for the confusion. FlashAttention-2 is compatible with quantized models. (actually, the attention calculation is performed in fp16 data type).

**Comment by shaojun** [comment]
@kq-chen the flash attention seems only support limited devices, and for consumer level GPU is only RTX3090 and RTX4090:
github.com/Dao-AILab/flash-attention?tab=readme-ov-file#nvidia-cuda-support     
does this mean `Qwen2-VL 7B with Int8 quantized` is not able to run any lower gpu card(RTX4080 with 16G memory and etc) ?

**Comment by HemanthoDarwin-RabertKennedy-ZS0532** [comment]
The input image context is also a reason for the high GPU consumption use the following code to optimize the image and it will consume the GPU less.

```
min_pixels = 256 * 28 * 28
max_pixels = 1280 * 28 * 28
processor = AutoProcessor.from_pretrained(
    "Qwen/Qwen2-VL-7B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels
)
```

**Comment by bhavyajoshi-mahindra** [comment]
How do you load and infer a custom GPTQ quantized Qwen2-VL model (not the default one) using Qwen2VLForConditionalGeneration in **WINDOWS**

I used the following code.

```
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info
import torch
import time
# We recommend enabling flash_attention_2 for better acceleration and memory saving, especially in multi-image and video scenarios.
DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"
print(DEVICE)
model_path = r"D:\amar\qwen2-vl-2\models\vinplate2-3000-4bit"
model = Qwen2VLForConditionalGeneration.from_pretrained(
    model_path,
    torch_dtype=torch.bfloat16, device_map= DEVICE, attn_implementation="flash_attention_2")
model.to(DEVICE)
# default: Load the model on the available device(s)
# model = Qwen2VLForConditionalGeneration.from_pretrained(
#     "Qwen/Qwen2-VL-7B-Instruct-GPTQ-Int4", torch_dtype="auto", device_map="auto"
# )
 
# The default range for the number of visual tokens per image in the model is 4-16384. You can set min_pixels and max_pixels according to your needs, such as a token count range of 256-1280, to balance speed and memory usage.
min_pixels = 256 * 28 * 28
max_pixels = 1280 * 28 * 28
processor = AutoProcessor.from_pretrained(
    model_path, min_pixels=min_pixels, max_pixels=max_pixels
)
 
messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": "[https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg"](https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg%22),
            },
            {"type": "text", "text": "Describe this image."},
        ],
    }
]
 
# Preparation for inference
text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)
image_inputs, video_inputs = process_vision_info(messages)
inputs = processor(
    text=[text],
    images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
).to(DEVICE)
t1 = time.time()
# Inference: Generation of the output
generated_ids = model.generate(**inputs, max_new_tokens=128)
generated_ids_trimmed = [
    out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
]
output_text = processor.batch_decode(
    generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
)
t2 = time.time()
print('Time Taken')
print(t2-t1)
print(output_text)
```

When I tried, I got the following error :

```
Traceback (most recent call last):
  File "D:\amar\qwen2-vl-2\infer_quan.py", line 9, in <module>
    model = Qwen2VLForConditionalGeneration.from_pretrained(
  File "C:\Users\amarg\anaconda3\envs\fresh\lib\site-packages\transformers\modeling_utils.py", line 3763, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory D:\amar\qwen2-vl-2\models\vinplate2-3000-4bit.
```

This are the files that are generated during the quantization 

![image](https://github.com/user-attachments/assets/8e09df46-a2d8-4bbc-b60b-cb0c87b14293)

Here is my environment

tokenizers==0.20.3
torch==2.4.1+cu121
torchaudio==2.4.1+cu121
torchvision==0.19.1+cu121
transformers==4.46.2
accelerate==1.1.1
auto_gptq==0.7.1
CUDA == 12.1

**Comment by bhavyajoshi-mahindra** [comment]
I tried to load my custom GPTQ quantized Qwen2-VL model but got the error. I am using **Windows**.
I have explained the issue here : https://github.com/QwenLM/Qwen2-VL/issues/520

**Comment by lebronjamesking** [comment]
Any updates though, it seems awq or gptq not working.

**Comment by ggsddu7** [comment]
通过修改transformer源码：可以让Qwen2.5-VL-72B-Instruct跑在单张3090显卡上。输出速度：单字/6s 最大内存30G
主要思路：nf4量化+80层decoder_layer逐层加载到显存计算
https://gist.github.com/ggsddu7/5d2320658afdc55a0a431016cef2915d
