### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by varungupta31** [QwenLM/Qwen2-VL#299]
I have been trying to fix this error for a while now, and the ongoing threads are of NO help.

I have checked these (and ALL issue on the HF community page for this model):
* https://github.com/QwenLM/Qwen2-VL/issues/288
* https://github.com/QwenLM/Qwen2-VL/issues/195
etc.

## Minimal Working Example

As taken directly from the model card on Huggingface,

``` python
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info

# default: Load the model on the available device(s)
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-7B-Instruct", torch_dtype="auto", device_map="auto"
)


# default processer
processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct")

processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels)

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg",
            },
            {"type": "text", "text": "Describe this image."},
        ],
    }
]

# Preparation for inference
text = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True
)
image_inputs, video_inputs = process_vision_info(messages)
inputs = processor(
    text=[text],
    images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
)
inputs = inputs.to("cuda")

# Inference: Generation of the output
generated_ids = model.generate(**inputs, max_new_tokens=128)
generated_ids_trimmed = [
    out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
]
output_text = processor.batch_decode(
    generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
)
print(output_text)
```

## Error

```bash
Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_section'}
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|_________________________________________________________________________________________________________| 5/5 [00:03<00:00,  1.54it/s]
Traceback (most recent call last):
  File "/home/varun/qwen2vlm/official.py", line 53, in <module>
    generated_ids = model.generate(**inputs, max_new_tokens=128)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/varun/.conda/envs/qwen2/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/varun/.conda/envs/qwen2/lib/python3.12/site-packages/transformers/generation/utils.py", line 2048, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/home/varun/.conda/envs/qwen2/lib/python3.12/site-packages/transformers/generation/utils.py", line 3044, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

I have tried :
- `model.eval()` mode
-  Tried with `float16` and also `bfloat16` with `flash_attention_2`
```
 model = Qwen2VLForConditionalGeneration.from_pretrained(
     "Qwen/Qwen2-VL-7B-Instruct",
     torch_dtype=torch.bfloat16,
     attn_implementation="flash_attention_2",
     device_map="auto" )
```
- Same issue in processing videos.
- Tried reinstalling flash attention (`pip install flash-attn --no-build-isolation`)

So far I have not been able to get this model working.

## Relevant Package Version

```bash
torch                     2.4.1
transformers              4.46.0.dev0
flash-attn                2.6.3
qwen-vl-utils             0.0.8
```

Kindly help,

Thanks.

**Comment by zhaolj** [comment]
the same issue

**Comment by varungupta31** [comment]
For the time being,


Changing:
```python
generated_ids = model.generate(**inputs, max_new_tokens=128)
```

To:

```python
generated_ids = model.generate(**inputs, max_new_tokens=128, do_sample=False)
```

i.e., `greedy decoding` solved the issue, but I am not sure why this is happening; not everyone may want to do greedy decoding.

This 'fix' was quite obvious from the error stack trace that sampling is where something is going wrong.

**Comment by geasyheart** [comment]
> Turn off `attn_implementation="flash_attention_2"` works for me.
 Turn on `attn_implementation="flash_attention_2"` works for me.

**Comment by jinghanSunn** [comment]
change to  torch_dtype=torch.bfloat16 works for me

**Comment by sralvins** [comment]
I didn't study it carefully, but I found that this error will not occur if only one GPU is used (set device_map=0 works for me)

If anyone has figured out why this happens, please enlighten me! 😄

**Comment by sleepwalker2017** [comment]
> I didn't look into the code carefully, but the error only appears with multiple GPUs (set device_map=0 works for me)
> 
> If anyone has figured out why this happens, please enlighten me! 😄

what's the meaning of set device_map=0 ?

**Comment by Oliver-CakesAndAle** [comment]
> I didn't look into the code carefully, but the error only appears with multiple GPUs (set device_map=0 works for me)
> 
> If anyone has figured out why this happens, please enlighten me! 😄

Same situation here! Have you found a way to avoid the error under mutiple GPUs setting?

**Comment by varungupta31** [comment]
So I did finally solve it - but heads up, there is/was no 'easy' fix to this, at least in my case.

I faced multiple issues even with the newer Qwen3 series, always struggling either with

- torch errors
- garbage outputs (if I solved torch errors - by nitpicking and trying random versions of `torch`/`numpy`/`accelerate`/`transformers`/`flash-attn`)
- or just stuck at inference.

The broader problem seemed to be, model would run fine on a single GPU, but not when sharded via `accelerate`


i.e,
```python
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-7B-Instruct", torch_dtype="auto"
).to(0)
```
would work, but

```python
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-7B-Instruct", torch_dtype="auto", device_map='auto'
)
```
would not.
(No error as such, but just stuck at inference forever)


I realised I'm running a quite old NVIDIA driver (535x) series, and these models require newer torch versions, which are optimal for the newer NVIDIA drivers - so I updated my NVIDIA driver to `570x` series and also updated the CUDA toolkit to 12.8 (from 12.2) and then things just work, with NVIDIA driver update being the main 'fix', and then re-installing the torch/transformer environment and trying the inference again.



I would encourage that you try if the above issue is faced by you too, and figure out if your current NVIDIA driver is 'outdated', then proceed to update the drivers.


Ofcourse, do this carefully - check your hardware, system, ensure compatibility - and follow the official documentations, and have system backups in place.



I wish there was some pip magic that could have solved this, but there isn't (or atleast, wasn't in my case). Even if you try torch setups with `conda` or even `pip` - which come their CUDA wheels, an old NVIDIA driver is still a bottleneck, which these wheels don't fix (afaik).

**Comment by AAnminy** [comment]
I also encountered the same error. My device is A100 40g. At first, my program can run normally, but then garbled characters appear. After debugging, I found that the execution time of the code `generated_ids = model.generate(**inputs, max_new_tokens=128) `becomes longer and garbled characters are generated, but it can run; occasionally, an error is found

> generated_ids = model.generate(**inputs, max_new_tokens=128)
> RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by AAnminy** [comment]
Indeed, inspired by a comment, the error disappeared when I only used one GPU. Could someone explain why this happened?

**Comment by sleepwalker2017** [comment]
you can try pp instead of tp



------------------ Original ------------------
From: Wenan ***@***.***&gt;
Date: Tue,Jul 15,2025 11:29 PM
To: QwenLM/Qwen2.5-VL ***@***.***&gt;
Cc: fade_away ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [QwenLM/Qwen2.5-VL] RuntimeError: probability tensor containseither `inf`, `nan` or element < 0 (Issue #299)



AAnminy left a comment (QwenLM/Qwen2.5-VL#299)
 
Indeed, inspired by a comment, the error disappeared when I only used one GPU. Could someone explain why this happened?
