### ISSUE TITLE
Bug in beam_search: memory allocation

### ISSUE THREAD

**Issue by greeksharifa** [QwenLM/Qwen2-VL#334]
If run this code:
```python
outputs = model.generate(**inputs, max_new_tokens=10, return_dict_in_generate=True, output_scores=True, do_sample=True, num_beams=2)
```
Then OutofMemoryError occurs:
```bash
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 538976288.13 GiB. GPU 1 has a total capacity of 47.54 GiB of which 43.55 GiB is free. Process 741857 has 3.97 GiB memory in use. Of the allocated memory 3.19 GiB is allocated by PyTorch, and 478.31 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

The `Tried to allocate 538976288.13 GiB.` message in error message is such ridiculous numeric. 

p.s. following code works.
```python
outputs = model.generate(**inputs, max_new_tokens=10, return_dict_in_generate=True, output_scores=True)
```

**Comment by HemanthoDarwin-RabertKennedy-ZS0532** [comment]
Use the Image optimization to do the minimal usage of GPU during inferencing.The code for the image optimization is as follow:

```
min_pixels = 256 * 28 * 28
max_pixels = 1280 * 28 * 28
processor = AutoProcessor.from_pretrained(
    "Qwen/Qwen2-VL-7B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels
)
```

**Comment by greeksharifa** [comment]
@HemanthoDarwin-RabertKennedy-ZS0532 Thanks you for your reply.

However, there's a new error: `RuntimeError: probability tensor contains either `inf`, `nan` or element < 0`.

```bash
Traceback (most recent call last):
  File "/home/ywjang/LBA_LAVIS_uncertainty_v2/main_multi_subqa.py", line 840, in <module>
    main()
  File "/home/ywjang/LBA_LAVIS_uncertainty_v2/main_multi_subqa.py", line 214, in main
    text_outputs_base, confidences_base = recomposer(vision, text_inputs)
  File "/home/ywjang/miniconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ywjang/miniconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ywjang/LBA_LAVIS_uncertainty_v2/models/model.py", line 482, in forward
    outputs = self.model.generate(
  File "/home/ywjang/miniconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ywjang/miniconda3/envs/qwen2vl/lib/python3.10/site-packages/transformers/generation/utils.py", line 2046, in generate
    result = self._beam_search(
  File "/home/ywjang/miniconda3/envs/qwen2vl/lib/python3.10/site-packages/transformers/generation/utils.py", line 3257, in _beam_search
    next_tokens = torch.multinomial(probs, num_samples=n_tokens_to_keep)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by Dineshkumar-Anandan-ZS0367** [comment]
I am getting accuracy loss to set the min and max pixels for this model. If not set i am getting cuda out of memory in A100 80GB machine also.

If i am setting min and max pixels that is given by huggingface, The model takes maximum 24GB worth cuda memory. But i had lots of accuracy loss on this.

**Comment by yidamyth** [comment]
> [@HemanthoDarwin-RabertKennedy-ZS0532](https://github.com/HemanthoDarwin-RabertKennedy-ZS0532) Thanks you for your reply.
> 
> However, there's a new error: `RuntimeError: probability tensor contains either `inf`, `nan` or element < 0`.
> 
> Traceback (most recent call last):
>   File "/home/ywjang/LBA_LAVIS_uncertainty_v2/main_multi_subqa.py", line 840, in <module>
>     main()
>   File "/home/ywjang/LBA_LAVIS_uncertainty_v2/main_multi_subqa.py", line 214, in main
>     text_outputs_base, confidences_base = recomposer(vision, text_inputs)
>   File "/home/ywjang/miniconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/ywjang/miniconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/ywjang/LBA_LAVIS_uncertainty_v2/models/model.py", line 482, in forward
>     outputs = self.model.generate(
>   File "/home/ywjang/miniconda3/envs/qwen2vl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/ywjang/miniconda3/envs/qwen2vl/lib/python3.10/site-packages/transformers/generation/utils.py", line 2046, in generate
>     result = self._beam_search(
>   File "/home/ywjang/miniconda3/envs/qwen2vl/lib/python3.10/site-packages/transformers/generation/utils.py", line 3257, in _beam_search
>     next_tokens = torch.multinomial(probs, num_samples=n_tokens_to_keep)
> RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

I also encountered the same problem. May I ask how you solved it?


Traceback (most recent call last):
  File "/home/yida/PyCharmProject/My_Paper/CoT-RLFuse/Model/Architecture/clip_model.py", line 685, in <module>
    y,_, extracted_batch_output = net(vis, ir)
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yida/PyCharmProject/My_Paper/CoT-RLFuse/Model/Architecture/clip_model.py", line 636, in forward
    extracted_output = batch_generate_and_extract_features(
  File "/home/yida/PyCharmProject/My_Paper/CoT-RLFuse/Model/Architecture/clip_model.py", line 178, in batch_generate_and_extract_features
    outputs = model.generate(
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/transformers/generation/utils.py", line 2223, in generate
    result = self._sample(
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/transformers/generation/utils.py", line 3257, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
