### ISSUE TITLE
不支持SM75？RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by maxin9966** [QwenLM/Qwen2-VL#44]
不支持SM75 ？有办法支持吗？速度慢点没事

## error:
Traceback (most recent call last):
  File "/home/ma/work/qwen2-vl/qwen-vl-demo.py", line 54, in <module>
    generated_ids = model.generate(**inputs, max_new_tokens=5000)
  File "/home/ma/miniconda3/envs/qwenvl/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ma/miniconda3/envs/qwenvl/lib/python3.9/site-packages/transformers/generation/utils.py", line 2015, in generate
    result = self._sample(
  File "/home/ma/miniconda3/envs/qwenvl/lib/python3.9/site-packages/transformers/generation/utils.py", line 2998, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by seanzhang-zhichen** [comment]
同报错，40G A100

**Comment by maxin9966** [comment]
## 40系卡也报错，gptq-int4模型：

Traceback (most recent call last):
  File "/home/ma/work/qwen2-vl/qwen-vl-demo.py", line 54, in <module>
    generated_ids = model.generate(**inputs, max_new_tokens=5000)
  File "/home/ma/miniconda3/envs/qwenvl/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ma/miniconda3/envs/qwenvl/lib/python3.9/site-packages/transformers/generation/utils.py", line 2015, in generate
    result = self._sample(
  File "/home/ma/miniconda3/envs/qwenvl/lib/python3.9/site-packages/transformers/generation/utils.py", line 2998, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by moyans** [comment]
V100 也是， gptq-int4,   grad_norm:  nan

**Comment by codeman0987** [comment]
A10同样报错，gptq-int4

**Comment by RobinRush** [comment]
> 同报错，40G A100

朋友解决了吗？
@seanzhang-zhichen

**Comment by yidamyth** [comment]
请问大家解决了吗，我修改了模型精度以及transformers降级到4.50以下，仍然存在该问题。最重要的是一台4090正常运行，另外一台出现异常。



Traceback (most recent call last):
  File "/home/yida/PyCharmProject/My_Paper/CoT-RLFuse/Model/Architecture/clip_model.py", line 685, in <module>
    y,_, extracted_batch_output = net(vis, ir)
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yida/PyCharmProject/My_Paper/CoT-RLFuse/Model/Architecture/clip_model.py", line 636, in forward
    extracted_output = batch_generate_and_extract_features(
  File "/home/yida/PyCharmProject/My_Paper/CoT-RLFuse/Model/Architecture/clip_model.py", line 178, in batch_generate_and_extract_features
    outputs = model.generate(
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/transformers/generation/utils.py", line 2223, in generate
    result = self._sample(
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/transformers/generation/utils.py", line 3257, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
