### ISSUE TITLE
VLLM 部署报错：Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")

### ISSUE THREAD

**Issue by jarrett-au** [QwenLM/Qwen2-VL#51]
拉取这个分支的VLLM: https://github.com/fyabc/vllm/tree/add_qwen2_vl_new
环境：Ubuntu + python 3.10

报错信息：
python -m vllm.entrypoints.openai.api_server --served-model-name Qwen2-VL-7B-Instruct --model /home/xxx/llms/Qwen2-VL-7B-Instruct
WARNING 08-31 15:52:50 _custom_ops.py:18] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 08-31 15:52:52 api_server.py:440] vLLM API server version 0.5.5
INFO 08-31 15:52:52 api_server.py:441] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, model='/home/xxx/llms/Qwen2-VL-7B-Instruct', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=['Qwen2-VL-7B-Instruct'], qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
INFO 08-31 15:52:52 api_server.py:144] Multiprocessing frontend to use ipc:///tmp/02c0dee1-0f8e-46ae-af65-2ae6d1fb498c for RPC Path.
INFO 08-31 15:52:52 api_server.py:161] Started engine process with PID 112581
WARNING 08-31 15:52:53 _custom_ops.py:18] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 08-31 15:52:54 llm_engine.py:212] Initializing an LLM engine (v0.5.5) with config: model='/home/xxx/llms/Qwen2-VL-7B-Instruct', speculative_config=None, tokenizer='/home/xxx/llms/Qwen2-VL-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen2-VL-7B-Instruct, use_v2_block_manager=False, num_scheduler_steps=1, enable_prefix_caching=False, use_async_output_proc=True)
INFO 08-31 15:52:55 model_runner.py:991] Starting to load model /home/xxx/llms/Qwen2-VL-7B-Instruct...
Loading safetensors checkpoint shards:   0% Completed | 0/5 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  20% Completed | 1/5 [00:00<00:01,  2.02it/s]
Loading safetensors checkpoint shards:  40% Completed | 2/5 [00:00<00:01,  2.87it/s]
Loading safetensors checkpoint shards:  60% Completed | 3/5 [00:01<00:00,  2.31it/s]
Loading safetensors checkpoint shards:  80% Completed | 4/5 [00:01<00:00,  1.95it/s]
Loading safetensors checkpoint shards: 100% Completed | 5/5 [00:02<00:00,  1.83it/s]
Loading safetensors checkpoint shards: 100% Completed | 5/5 [00:02<00:00,  1.99it/s]

INFO 08-31 15:52:58 model_runner.py:1002] Loading model weights took 15.7193 GB
ERROR 08-31 15:52:59 _custom_ops.py:37] Error in calling custom op gelu_quick: '_OpNamespace' '_C' object has no attribute 'gelu_quick'
ERROR 08-31 15:52:59 _custom_ops.py:37] Possibly you have built or installed an obsolete version of vllm.
ERROR 08-31 15:52:59 _custom_ops.py:37] Please try a clean build and install of vllm,or remove old built files such as vllm/*cpython*.so and build/ .
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxx/llms/vllm/vllm/entrypoints/openai/rpc/server.py", line 236, in run_rpc_server
    server = AsyncEngineRPCServer(async_engine_args, usage_context, rpc_path)
  File "/home/xxx/llms/vllm/vllm/entrypoints/openai/rpc/server.py", line 34, in __init__
    self.engine = AsyncLLMEngine.from_engine_args(
  File "/home/xxx/llms/vllm/vllm/engine/async_llm_engine.py", line 750, in from_engine_args
    engine = cls(
  File "/home/xxx/llms/vllm/vllm/engine/async_llm_engine.py", line 641, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/xxx/llms/vllm/vllm/engine/async_llm_engine.py", line 850, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/xxx/llms/vllm/vllm/engine/async_llm_engine.py", line 262, in __init__
    super().__init__(*args, **kwargs)
  File "/home/xxx/llms/vllm/vllm/engine/llm_engine.py", line 316, in __init__
    self._initialize_kv_caches()
  File "/home/xxx/llms/vllm/vllm/engine/llm_engine.py", line 451, in _initialize_kv_caches
    self.model_executor.determine_num_available_blocks())
  File "/home/xxx/llms/vllm/vllm/executor/gpu_executor.py", line 114, in determine_num_available_blocks
    return self.driver_worker.determine_num_available_blocks()
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/llms/vllm/vllm/worker/worker.py", line 222, in determine_num_available_blocks
    self.model_runner.profile_run()
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/llms/vllm/vllm/worker/model_runner.py", line 1209, in profile_run
    self.execute_model(model_input, kv_caches, intermediate_tensors)
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/llms/vllm/vllm/worker/model_runner.py", line 1536, in execute_model
    hidden_or_intermediate_states = model_executable(
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/llms/vllm/vllm/model_executor/models/qwen2_vl.py", line 821, in forward
    image_embeds = self._process_image_input(image_input)
  File "/home/xxx/llms/vllm/vllm/model_executor/models/qwen2_vl.py", line 754, in _process_image_input
    image_embeds = self.visual(pixel_values,
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/llms/vllm/vllm/model_executor/models/qwen2_vl.py", line 481, in forward
    x = blk(x, cu_seqlens=cu_seqlens, rotary_pos_emb=rotary_pos_emb)
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/llms/vllm/vllm/model_executor/models/qwen2_vl.py", line 277, in forward
    x = x + self.mlp(self.norm2(x))
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/llms/vllm/vllm/model_executor/models/qwen2_vl.py", line 124, in forward
    x_parallel = self.act(x_parallel)
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/llms/vllm/vllm/model_executor/custom_op.py", line 14, in forward
    return self._forward_method(*args, **kwargs)
  File "/home/xxx/llms/vllm/vllm/model_executor/layers/activation.py", line 155, in forward_cuda
    ops.gelu_quick(out, x)
  File "/home/xxx/llms/vllm/vllm/_custom_ops.py", line 38, in wrapper
    raise e
  File "/home/xxx/llms/vllm/vllm/_custom_ops.py", line 29, in wrapper
    return fn(*args, **kwargs)
  File "/home/xxx/llms/vllm/vllm/_custom_ops.py", line 65, in gelu_quick
    torch.ops._C.gelu_quick(out, x)
  File "/home/xxx/.conda/envs/vllm/lib/python3.10/site-packages/torch/_ops.py", line 1170, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' '_C' object has no attribute 'gelu_quick'
ERROR 08-31 15:53:02 api_server.py:171] RPCServer process died before responding to readiness probe

**Comment by zhangzhiqiangcs** [comment]
试试在本地执行下 `pip install -e . `，这样能编译出对应的 C 扩展文件

**Comment by caofei88** [comment]
Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'").  Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'"). 同上， 如何解决

**Comment by 1305154073** [comment]
请问下，问题解决了吗？

**Comment by fyabc** [comment]
这可能是vllm编译时出现的问题，请卸载掉现有的安装，删除掉`vllm/*cpython*.so` 和`build/`文件，然后重新编译。
