### ISSUE TITLE
给的requirements_web_demo.txt文件有问题吗

### ISSUE THREAD

**Issue by bisque-qwe** [QwenLM/Qwen2-VL#534]
直接使用pip install -r requirements_web_demo.txt,运行测试demo失败

**Comment by bisque-qwe** [comment]
Traceback (most recent call last):
  File "/root/anaconda3/envs/qwen2-vl/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1778, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/qwen2-vl/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/anaconda3/envs/qwen2-vl/lib/python3.11/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 43, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/root/anaconda3/envs/qwen2-vl/lib/python3.11/site-packages/transformers/modeling_utils.py", line 48, in <module>
    from .loss.loss_utils import LOSS_MAPPING
  File "/root/anaconda3/envs/qwen2-vl/lib/python3.11/site-packages/transformers/loss/loss_utils.py", line 19, in <module>
    from .loss_deformable_detr import DeformableDetrForObjectDetectionLoss, DeformableDetrForSegmentationLoss
  File "/root/anaconda3/envs/qwen2-vl/lib/python3.11/site-packages/transformers/loss/loss_deformable_detr.py", line 4, in <module>
    from ..image_transforms import center_to_corners_format
  File "/root/anaconda3/envs/qwen2-vl/lib/python3.11/site-packages/transformers/image_transforms.py", line 22, in <module>
    from .image_utils import (
  File "/root/anaconda3/envs/qwen2-vl/lib/python3.11/site-packages/transformers/image_utils.py", line 58, in <module>
    from torchvision.transforms import InterpolationMode
  File "/root/anaconda3/envs/qwen2-vl/lib/python3.11/site-packages/torchvision/__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/qwen2-vl/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 163, in <module>
    @torch.library.register_fake("torchvision::nms")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'torch.library' has no attribute 'register_fake'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/panzhichun/Qwen2-VL-72B-Instruct-AWQ/test_qwen_vl.py", line 1, in <module>
    from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/root/anaconda3/envs/qwen2-vl/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1767, in __getattr__
    value = getattr(module, name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/qwen2-vl/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1766, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/qwen2-vl/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1780, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.qwen2_vl.modeling_qwen2_vl because of the following error (look up to see its traceback):
module 'torch.library' has no attribute 'register_fake'
