### ISSUE TITLE
ValueError: Video features and video tokens do not match: tokens: 0, features 1152

### ISSUE THREAD

**Issue by Cb1ock** [QwenLM/Qwen2-VL#549]
I use the official code to inference, which show as below:
```python
import json
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info
import torch
import os

# default: Load the model on the available device(s)
# model = Qwen2VLForConditionalGeneration.from_pretrained(
#     "./Qwen2-VL-72B-Instruct", torch_dtype="auto", device_map="auto"
# )

# We recommend enabling flash_attention_2 for better acceleration and memory saving, especially in multi-image and video scenarios.
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "./Qwen2-VL-72B-Instruct",
    torch_dtype=torch.bfloat16,
    attn_implementation="flash_attention_2",
    device_map="auto",
)

# default processer
processor = AutoProcessor.from_pretrained("./Qwen2-VL-72B-Instruct")

# The default range for the number of visual tokens per image in the model is 4-16384. You can set min_pixels and max_pixels according to your needs, such as a token count range of 256-1280, to balance speed and memory usage.
# min_pixels = 256*28*28
# max_pixels = 1280*28*28
# processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-72B-Instruct", min_pixels=min_pixels, max_pixels=max_pixels)
import random
messages = []
video_path = '/home/u2023170744/data/CelebV-Text/video'
video_files = [f for f in os.listdir(video_path) if f.endswith('.mp4')]

# 随机选择一个视频
random_video = random.choice(video_files)

messages.append(
    {
        "role": "user",
        "content": [
            {
                "type": "video",
                "video": f"file:///{video_path}/{random_video}",
                "max_pixels": 360 * 420,
                "fps": 12,
            },
            {"type": "text", "text": "Please carefully analyze the following video content, focusing on the **emotional information** expressed in it. Please describe the facial movements, emotional states, changes in emotions of the characters in the video, and possible causes of these emotions."},
        ],
    }
)

results = []

# Process each batch

texts = [
    processor.apply_chat_template(msg, tokenize=False, add_generation_prompt=True)
    for msg in messages
]
_, video_inputs = process_vision_info(messages)

# # Debugging information
# print(f"Processed video inputs: {video_inputs}")
# print(f"Number of video inputs: {len(video_inputs)}")
# for i, video_input in enumerate(video_inputs):
#     print(f"Shape of video input {i}: {video_input.shape}")

inputs = processor(
    text=texts,
    #images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
)

# # Debugging information
# print(f"Processor inputs: {inputs}")
# print(f"Input IDs: {inputs.input_ids}")
# print(f"Pixel Values Videos: {inputs.pixel_values_videos}")
# print(f"Video Grid THW: {inputs.video_grid_thw}")

inputs = inputs.to("cuda")
print(type(inputs))
#print(f'input {inputs.shape}')
# Batch Inference
generated_ids = model.generate(**inputs, max_new_tokens=128)
generated_ids_trimmed = [
    out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
]
output_texts = processor.batch_decode(
    generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
)
results.extend(output_texts)

# Save results to JSON file
with open('output.json', 'w') as f:
    json.dump(results, f, ensure_ascii=False, indent=4)
```
But, somehow , a ValueError has appeared:
```
(MLLM) ➜  qwen2-vl-72b git:(master) ✗ python video_caption_inference.py
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 38/38 [00:51<00:00,  1.34s/it]
qwen-vl-utils using torchvision to read video.
<class 'transformers.feature_extraction_utils.BatchFeature'>
Traceback (most recent call last):
  File "/home/u2023170720/qwen2-vl-72b/video_caption_inference.py", line 84, in <module>
    generated_ids = model.generate(**inputs, max_new_tokens=128)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u2023170744/.conda/envs/MLLM/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u2023170744/.conda/envs/MLLM/lib/python3.12/site-packages/transformers/generation/utils.py", line 2232, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/home/u2023170744/.conda/envs/MLLM/lib/python3.12/site-packages/transformers/generation/utils.py", line 3223, in _sample
    outputs = self(**model_inputs, return_dict=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u2023170744/.conda/envs/MLLM/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u2023170744/.conda/envs/MLLM/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u2023170744/.conda/envs/MLLM/lib/python3.12/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u2023170744/.conda/envs/MLLM/lib/python3.12/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1708, in forward
    raise ValueError(
ValueError: Video features and video tokens do not match: tokens: 0, features 1152
```

**Comment by LeeOrange-is-me** [comment]
so how do you solve that please?

**Comment by Cb1ock** [comment]
In order to help others who encounter the same issue, I’m sharing my solution and the current batch inference script below.

My solution: This issue was caused by an incorrect data type being passed to the messages.append() function — it was appending a dictionary instead of a list containing a dictionary, which might be required by the model or API being used.

To fix it, simply change:
```python
messages.append( 
    {
        "role": "user",
        "content": [
            {
                "type": "video",
                "video": f"file:///{video_path}/{random_video}",
                "max_pixels": 360 * 420,
                "fps": 12,
            },
            {
                "type": "text",
                "text": "This is a prompt."
            },
        ],
    }
)
```
to:
```python
messages.append([
    {
        "role": "user",
        "content": [
            {
                "type": "video",
                "video": f"file:///{video_path}/{random_video}",
                "max_pixels": 360 * 420,
                "fps": 12,
            },
            {
                "type": "text",
                "text": "This is a prompt."
            },
        ],
    }
])
```
and the script should work as expected.

My current batch inference script:
```python
import json
import argparse
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info
import torch
import os
from tqdm import tqdm
import torch.distributed as dist
import torch.multiprocessing as mp
from torch.nn.parallel import DistributedDataParallel as DDP
import logging
from collections import defaultdict, OrderedDict
import re
import pandas as pd

def setup(rank, world_size):
    # Initialize distributed environment
    dist.init_process_group(
        backend="nccl",
        init_method="env://",
        rank=rank,
        world_size=world_size
    )
    torch.cuda.set_device(rank)

def cleanup():
    # Clean up the distributed environment
    dist.destroy_process_group()

def get_processed_videos(log_file):
    # Retrieve processed videos from the log file
    processed_videos = set()
    with open(log_file, 'r', encoding='utf-8') as file:
        for line in file:
            match = re.search(r"Result: \{['\"]name['\"]: ['\"](\S+)['\"], ['\"]video_caption['\"]: ['\"](.+?)['\"]\}", line)
            if match:
                name = match.group(1)
                processed_videos.add(name)
    return processed_videos

def main(rank, world_size, args, result_queue):
    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s %(levelname)s [Process %(process)d] %(message)s',
        filename='output.log',
        filemode='a'
    )
    logger = logging.getLogger()

    setup(rank, world_size)

    # Convert torch_dtype argument
    if args.torch_dtype == "float16":
        torch_dtype = torch.float16
    elif args.torch_dtype == "bfloat16":
        torch_dtype = torch.bfloat16
    else:
        raise ValueError(f"Unsupported torch_dtype: {args.torch_dtype}")

    # Load the model
    model = Qwen2VLForConditionalGeneration.from_pretrained(
        args.model_path,
        torch_dtype=torch_dtype,
        attn_implementation="flash_attention_2",
    )

    model = model.to(rank)
    model.eval()
    model = DDP(model, device_ids=[rank])

    processor = AutoProcessor.from_pretrained(args.model_path)

    # Retrieve processed videos
    log_file = 'output.log'
    processed_videos = get_processed_videos(log_file)
    print(f'{len(processed_videos)} videos have been processed.')

    # Retrieve all video files
    csv_file_path = args.video_path
    df = pd.read_csv(csv_file_path, sep=' ', header=None)
    all_videos = df[0].tolist()

    all_videos = [video for video in all_videos if video not in processed_videos]
    # Distribute video files based on rank
    videos_to_process = all_videos[rank::world_size]
    print(f'Process {rank} will process {len(videos_to_process)} videos.')

    # Prepare messages
    messages = []
    for video in videos_to_process:
        video_path = video
        messages.append([
            {
                "role": "user",
                "content": [
                    {
                        "type": "video",
                        "video": f"file:///{video_path}",
                        "max_pixels": 224 * 224,
                        "fps": args.fps,
                        "max_duration": 5,
                    },
                    {
                        "type": "text",
                        "text": (
                            "Please carefully analyze the following video content with a focus on the emotional information expressed. "
                            "Perform the following tasks: "
                            "1. Describe the facial movements and expressions of the characters in the video, noting any significant changes. "
                            "2. Assess the emotional state of the characters, using their facial expressions and body language as evidence. "
                            "3. Identify and describe any changes in the characters' emotional states throughout the video. "
                            "Ensure that all judgments are based on observable evidence within the video, avoiding speculation."
                        )
                    },
                ],
                "video_name": video
            }]
        )
    print(f'Process {rank} got {len(messages)} videos to process.')

    # Dynamically adjust batch size
    max_batch_size = args.batch_size
    min_batch_size = 1
    current_batch_size = max_batch_size

    all_batch_results = []

    # Process each batch
    with tqdm(total=len(messages), desc=f"Processing Batches on rank {rank}") as pbar:
        i = 0
        while i < len(messages):
            batch = messages[i:i + current_batch_size]
            texts = [
                processor.apply_chat_template(msg, tokenize=False, add_generation_prompt=True)
                for msg in batch
            ]
            try:
                _, video_inputs = process_vision_info(batch)
                inputs = processor(
                    text=texts,
                    videos=video_inputs,
                    padding=True,
                    return_tensors="pt",
                )
                inputs = inputs.to(rank)

                with torch.no_grad():
                    # Inference
                    generated_ids = model.module.generate(
                        **inputs,
                        max_new_tokens=args.max_new_tokens,
                        eos_token_id=model.module.config.eos_token_id
                    )
                    generated_ids_trimmed = [
                        out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
                    ]
                    output_texts = processor.batch_decode(
                        generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
                    )

                    # Save results
                    batch_results = []
                    for msg, output_text in zip(batch, output_texts):
                        result = {
                            "name": msg[0]["video_name"],
                            "video_caption": output_text
                        }
                        batch_results.append(result)
                        logger.info(f"Result: {json.dumps(result)}")

                    all_batch_results.extend(batch_results)
                    i += current_batch_size
                    current_batch_size = min(current_batch_size * 2, max_batch_size)  # Increase batch size
            except KeyError as e:
                logger.error(f"KeyError: {e}")
                i += current_batch_size  # Skip current batch
            except RuntimeError as e:
                if "CUDA out of memory" in str(e):
                    current_batch_size = max(current_batch_size // 2, min_batch_size)  # Decrease batch size
                    if current_batch_size < min_batch_size:
                        logger.error(f"CUDA out of memory error for batch: {batch}")
                        raise e
                else:
                    logger.error(f"Runtime error for batch: {batch}")
                    logger.error(e)
                    i += current_batch_size  # Skip current batch
            pbar.update(len(batch))

    # Put results into the queue
    result_queue.put(all_batch_results)

    cleanup()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Video Caption Inference")
    parser.add_argument('--model_path', type=str, default="./Qwen2-VL-7B-Instruct", help="Path to the model")
    parser.add_argument('--video_path', type=str, default="./vox_celeb2_sample_200k.csv", help="Path to the video files")
    parser.add_argument('--output_file', type=str, default="video_caption.json", help="Path to the output JSON file")
    parser.add_argument('--batch_size', type=int, default=16, help="Batch size for processing")
    parser.add_argument('--max_new_tokens', type=int, default=256, help="Maximum number of new tokens to generate")
    parser.add_argument('--torch_dtype', type=str, default="bfloat16", help="Torch data type (e.g., float16, bfloat16)")
    parser.add_argument('--fps', type=float, default=3, help="Frames per second to extract from video")
    parser.add_argument('--world_size', type=int, default=torch.cuda.device_count(), help="Number of GPUs to use")
    args = parser.parse_args()

    # Set environment variables
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'

    # Create a queue
    manager = mp.Manager()
    result_queue = manager.Queue()

    # Launch multiple processes
    mp.spawn(main, args=(args.world_size, args, result_queue), nprocs=args.world_size, join=True)

    # Collect results
    all_results = []
    while not result_queue.empty():
        all_results.extend(result_queue.get())

    # Write results to the output file
    with open(args.output_file, 'w') as f:
        json.dump(all_results, f, ensure_ascii=False, indent=4)
```

**Comment by LeeOrange-is-me** [comment]
😭 我解决了 为什么Qwen2-vl-7B出错了。
废话不多说，先看我的代码
```python 
model_name = '/path/to/Qwen2-VL-7B' 
processor = AutoProcessor.from_pretrained(model_name,trust_remote_code=True)
model = Qwen2VLForConditionalGeneration.from_pretrained(model_name, device_map="auto", trust_remote_code=True)

messages = [
    {
        "role": "user",
        "content":[ 
        {
        "type":"text" ,"text":"TELL ME WHY!!!!"
        }
    ]
    }
]

text_input = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
# About the text_input, it is ""!  This is the key point, you can print(text_input)
image_inputs, video_inputs = process_vision_info(messages)
inputs = processor(
            text=[text_input],
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt")
inputs = inputs.to("cuda:0")
output_ids =model.generate(**inputs, max_new_tokens=256)
generated_ids_trimmed = [output_ids[len(input_ids):] for input_ids, output_ids in zip(inputs.input_ids, output_ids )]
response= processor.batch_decode(generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=True)
``` 
it returns :
```APL
Traceback (most recent call last):
  File "/data/lsd/work/LLM/JailBreakV_28K/attack_models/Qwen.py", line 64, in <module>
    ret = model.inference("/data/lsd/work/LLM/JailBreakV_28K/JailBreakV_28k/query_related/SD_related_0.png", "hi!describe the picture")
  File "/data/lsd/work/LLM/JailBreakV_28K/attack_models/Qwen.py", line 56, in inference
    output_ids =self. model.generate(**inputs, max_new_tokens=256)
  File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 2465, in generate
    result = self._sample(
  File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 3424, in _sample
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1764, in prepare_inputs_for_generation
    model_inputs = super().prepare_inputs_for_generation(
  File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 507, in prepare_inputs_for_generation
    inputs_embeds, input_ids = self._cache_dependant_input_preparation(
  File "/data/lsd/anaconda3/envs/jbv/lib/python3.9/site-packages/transformers/generation/utils.py", line 406, in _cache_dependant_input_preparation
    or (cache_position[-1] >= input_ids.shape[1])  # Exception 3.(This may be varified due to your code.)
```
It may be due to the model in `huggingface` being something wrong. ~ If the `chat_template.json` in your model path is:
```
{ 
 "chat_template": "{% if messages is string %}{{ messages }}{% else %}{% for content in messages %}{% if content['type'] == 'image' or 'image' in content or 'image_url' in content %}<|vision_start|><|image_pad|><|vision_end|>{% elif content['type'] == 'video' or 'video' in content %}<|vision_start|><|video_pad|><|vision_end|>{% elif 'text' in content %}{{ content['text'] }}{% endif %}{% endfor %}{% endif %}" 
 } 
```
And you should use `chat_template.json` in `Qwen2.5` or other versions. I copy the belowing:
```
{
    "chat_template": "{% set image_count = namespace(value=0) %}{% set video_count = namespace(value=0) %}{% for message in messages %}{% if loop.first and message['role'] != 'system' %}<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n{% endif %}<|im_start|>{{ message['role'] }}\n{% if message['content'] is string %}{{ message['content'] }}<|im_end|>\n{% else %}{% for content in message['content'] %}{% if content['type'] == 'image' or 'image' in content or 'image_url' in content %}{% set image_count.value = image_count.value + 1 %}{% if add_vision_id %}Picture {{ image_count.value }}: {% endif %}<|vision_start|><|image_pad|><|vision_end|>{% elif content['type'] == 'video' or 'video' in content %}{% set video_count.value = video_count.value + 1 %}{% if add_vision_id %}Video {{ video_count.value }}: {% endif %}<|vision_start|><|video_pad|><|vision_end|>{% elif 'text' in content %}{{ content['text'] }}{% endif %}{% endfor %}<|im_end|>\n{% endif %}{% endfor %}{% if add_generation_prompt %}<|im_start|>assistant\n{% endif %}"
}
``` 
Then you should replace your `chat_template.json` with the bellow one.
And this may help you.
