### ISSUE TITLE
添加Flash-attention2后，使用Qwen2-7B-VL进行推理，会报错

### ISSUE THREAD

**Issue by LKAMING97** [QwenLM/Qwen2-VL#565]
Traceback (most recent call last):
  File "/root/autodl-tmp/Lumina-mGPT/infer_nlvr2.py", line 114, in <module>
    generated_ids = model.generate(**inputs, max_new_tokens=100)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/transformers/generation/utils.py", line 2253, in generate
    result = self._sample(
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/transformers/generation/utils.py", line 3254, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1661, in forward
    image_embeds = self.visual(pixel_values, grid_thw=image_grid_thw)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1038, in forward
    hidden_states = blk(hidden_states, cu_seqlens=cu_seqlens, rotary_pos_emb=rotary_pos_emb)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 431, in forward
    hidden_states = hidden_states + self.attn(
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 376, in forward
    attn_output = flash_attn_varlen_func(q, k, v, cu_seqlens, cu_seqlens, max_seqlen, max_seqlen).reshape(
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 1407, in flash_attn_varlen_func
    return FlashAttnVarlenFunc.apply(
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 896, in forward
    out_padded, softmax_lse, S_dmask, rng_state = _wrapped_flash_attn_varlen_forward(
  File "/root/miniconda3/envs/my-env/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 164, in _flash_attn_varlen_forward
    out, softmax_lse, S_dmask, rng_state = flash_attn_cuda.varlen_fwd(
RuntimeError: cu_seqlens_q must have dtype int32

**Comment by LKAMING97** [comment]
单卡A100进行推理
```python
import torch
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info
from datasets import load_dataset
from sklearn.metrics import accuracy_score
from PIL import Image
import io
from datetime import datetime
from tqdm import tqdm
import multiprocessing as mp
import os

os.environ["TOKENIZERS_PARALLELISM"] = "True"
import warnings

warnings.filterwarnings('ignore')

##  nlvr2 数据
def accuracy(y_true, y_pred):
    return accuracy_score(y_true, y_pred)


def open_image(image_data):
    return Image.open(io.BytesIO(image_data["bytes"]))


DATA_PATH = "/root/autodl-tmp/Lumina-mGPT/NLVR2/datasets--TIGER-Lab--NLVR2/nlvr2/"
MODEL_PATH = "/root/autodl-tmp/Lumina-mGPT/lumina_mgpt/Qwen/Qwen2-VL-7B-Instruct"

ds = load_dataset(path=DATA_PATH)
test_datas = ds["test"].to_pandas()
model = Qwen2VLForConditionalGeneration.from_pretrained(
    MODEL_PATH, torch_dtype=torch.bfloat16, device_map="auto",attn_implementation="flash_attention_2"
)

min_pixels = 256 * 28 * 28
max_pixels = 1280 * 28 * 28
processor = AutoProcessor.from_pretrained(
    MODEL_PATH, min_pixels=min_pixels, max_pixels=max_pixels
)

# 答案
answer = test_datas['answer'].tolist()
answer = [1 if i == "A" else 0 for i in answer]

# 设置batch_size
batch_size = 2
num_samples = len(test_datas)
num_batches = num_samples // batch_size + (1 if num_samples % batch_size!= 0 else 0)

results = []


with tqdm(total=num_samples) as pbar:
    for batch_idx in range(num_batches):
        start_idx = batch_idx * batch_size
        end_idx = min((batch_idx + 1) * batch_size, num_samples)

        batch_conversations = []
        for index in range(start_idx, end_idx):
            row = test_datas.iloc[index]
            text = row["question"].replace("<image>", "")
            images = row["images"]

            with mp.Pool(processes=2) as pool:
                opened_images = pool.map(open_image, images)

            options = "".join(row["options"].tolist())

            conversation = [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "image", "image": opened_images[0]
                        },
                        {
                            "type": "image", "image": opened_images[1]
                        },
                        {"type": "text", "text": f"Read the text and pictures and output the correct options below {options}, text:{text} "},
                    ],
                }
            ]


            batch_conversations.append(conversation)

            pbar.update(1)

        batch_messages = batch_conversations
        texts = [
            processor.apply_chat_template(msg, tokenize=False, add_generation_prompt=True)
            for msg in batch_messages
        ]
        image_inputs, video_inputs = process_vision_info(batch_messages)
        inputs = processor(
            text=texts,
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt",
        )
        inputs = inputs.to("cuda")

        # Batch Inference
        generated_ids = model.generate(**inputs, max_new_tokens=100)
        generated_ids_trimmed = [
            out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
        ]
        output_texts = processor.batch_decode(
            generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )
        print(output_texts)
        results.append(output_texts)
        ```

**Comment by luosting** [comment]
我现在两台不同服务器多卡加载模型推理要么一直没结果要么直接弹出各种错误，只能单卡，但是单卡又不能加载72B模型了，这模型是不是有点挑硬件啊

**Comment by sjghh** [comment]
> 我现在两台不同服务器多卡加载模型推理要么一直没结果要么直接弹出各种错误，只能单卡，但是单卡又不能加载72B模型了，这模型是不是有点挑硬件啊

兄弟解决了吗？/(ㄒoㄒ)/~~

**Comment by LKAMING97** [comment]
> > 我现在两台不同服务器多卡加载模型推理要么一直没结果要么直接弹出各种错误，只能单卡，但是单卡又不能加载72B模型了，这模型是不是有点挑硬件啊
> 
> 兄弟解决了吗？/(ㄒoㄒ)/~~

我也没有，放弃了，直接调用api了...

**Comment by TongxingJin** [comment]
> > 我现在两台不同服务器多卡加载模型推理要么一直没结果要么直接弹出各种错误，只能单卡，但是单卡又不能加载72B模型了，这模型是不是有点挑硬件啊
> 
> 兄弟解决了吗？/(ㄒoㄒ)/~~

兄弟解决了吗
