### ISSUE TITLE
llamafactory微调后无法加载模型

### ISSUE THREAD

**Issue by Youmo1** [QwenLM/Qwen2-VL#581]
2024-12-05 08:40:12.385 | INFO     | __main__:load_model:23 - begin load Qwen2-VL-7B-Instruct model.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.60it/s]
Traceback (most recent call last):
  File "model.py", line 126, in <module>
    qwenvlx = QwenvlModel()
  File "/opt/chat-vlm-w-rag/src/base_config.py", line 17, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "model.py", line 20, in __init__
    self.load_model(self.model_dir)
  File "model.py", line 30, in load_model
    self.processor = AutoProcessor.from_pretrained(model_dir, min_pixels=min_pixels, max_pixels=max_pixels)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/processing_auto.py", line 324, in from_pretrained
    return processor_class.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/processing_utils.py", line 894, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/processing_utils.py", line 940, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 2202, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 2436, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/qwen2/tokenization_qwen2_fast.py", line 120, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_fast.py", line 115, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: data did not match any variant of untagged enum ModelWrapper at line 757371 column 3

**Comment by Nwaf-sl** [comment]
同样的问题，使用AutoProcessor.from_pretrained加载原始的tokenizer可以得到解决，请问有没有更好的解决方法？

**Comment by zhangboshen** [comment]
+1 同样的问题，qwen2-vl使用lora finetune后无法出现这个问题

**Comment by XiaokangLei** [comment]
Lora微调的先合并权重，再调用推理，不要直接用

**Comment by Youmo1** [comment]
> Lora微调的先合并权重，再调用推理，不要直接用

合并了报这个错误，感觉是transformers的版本问题

**Comment by Youmo1** [comment]
> 同样的问题，使用AutoProcessor.from_pretrained加载原始的tokenizer可以得到解决，请问有没有更好的解决方法？

什么意思？我降低transformers后，问题得到了解决

**Comment by Road2Redemption** [comment]
@XiaokangLei 请问现在支持直接用adapter推理了吗？还是说必须要先merge？
