### ISSUE TITLE
容器部署Qwen2-VL-2B-Instruct 打包镜像迁移到无互联网设备调用报错

### ISSUE THREAD

**Issue by sujunze** [QwenLM/Qwen2-VL#602]
程序源码如下：
```python
import os
import uvicorn
import logging
from fastapi import FastAPI, Depends
from fastapi import Form
import traceback
from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info
import json

from modelscope import snapshot_download
model_dir = snapshot_download("qwen/Qwen2-VL-2B-Instruct")
# model_dir = "/root/.cache/modelscope/hub/qwen/Qwen2-VL-2B-Instruct"
# default: Load the model on the available device(s)
model = Qwen2VLForConditionalGeneration.from_pretrained(
    model_dir, torch_dtype="auto", device_map="auto"
)
processor = AutoProcessor.from_pretrained(model_dir)
DEBUG = os.getenv('API_DEBUG', 'false').lower() == 'true'
NUM_WORKERS = int(os.getenv('NUM_WORKERS', '1'))
logger = logging.getLogger('uvicorn')

def show_log(msg):
    if DEBUG:
        logger.info(msg)

# noinspection HttpUrlsUsage
app = FastAPI(
    debug=DEBUG,
    title='千问大模型',
    description='千问大模型',
    version='beta',
    docs_url='/docs' if DEBUG else None,
    redoc_url=None,
    swagger_ui_oauth2_redirect_url=None,
    swagger_ui_init_oauth=None,
)


@app.post(path='/qwen', summary='千问大模型')
async def qwen(
        source_img: str = Form(..., description='待测图片，base64编码，支持JPEG/PNG/webp格式'),
        query: str = Form(..., description='问题')
):
    try:
        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": "data:image;base64," + source_img},
                    {"type": "text", "text": query},
                ],
            }
        ]
        text = processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        image_inputs, video_inputs = process_vision_info(messages)
        inputs = processor(
            text=[text],
            images=image_inputs,
            videos=video_inputs,
            padding=True,
            return_tensors="pt",
        )

        # 确保所有输入数据都转移到 GPU (cuda)
        inputs = inputs.to("cuda")
        results = {"code": 0, "msg": "成功"}

        # 执行生成
        generated_ids = model.generate(**inputs, max_new_tokens=128)

        # 处理输出
        generated_ids_trimmed = [
            out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
        ]
        output_text = processor.batch_decode(
            generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
        )
        results["data"] = output_text
        return json.dumps(results)

    except Exception as e:
        traceback.print_exc()
        results = {"code": -1, "msg": "失败", "data": []}
        return json.dumps(results)


if __name__ == '__main__':
    uvicorn.run(
        app='qwen:app',
        host='0.0.0.0',
        port=50000,
        reload=DEBUG,
        workers=0 if DEBUG else NUM_WORKERS,
        access_log=DEBUG
    )
报错内容如下：
Traceback (most recent call last):
  File "/home/qwen.py", line 72, in qwen
    generated_ids = model.generate(**inputs, max_new_tokens=128)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/generation/utils.py", line 2252, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/generation/utils.py", line 3251, in _sample
    outputs = self(**model_inputs, return_dict=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1707, in forward
    position_ids, rope_deltas = self.get_rope_index(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1511, in get_rope_index
    input_ids = input_ids[attention_mask[i] == 1]
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:0)

**Comment by inf3rnus** [comment]
I have the same problem, except with 4 T4 gpus

**Comment by inf3rnus** [comment]
@sujunze this is the fix:

```
from torch import nn

class MonkeyPatchedEmbedding(nn.Module):
    def __init__(self, original_embed_tokens, device):
        super().__init__()
        self.original_embed_tokens = original_embed_tokens
        self.device = device

    def forward(self, *args, **kwargs):
        # Use the original embedding layer but ensure output is on the correct device
        tensors = self.original_embed_tokens(*args, **kwargs)
        return tensors.to(self.device)

pipe = pipeline(
    "image-text-to-text", model=model_id, processor=processor, **kwargs
)

# NOTE monkey patch the bad embed layer that points to device 1, the forward() logic demands that
# these be on the same device as operations are performed on the attention mask and input_ids, which reside on the model's default device
# the problem is accelerate gets that one aspect of the device map wrong when it tries to infer where each layer should go.
original_embed_tokens = pipe.model.model.embed_tokens

pipe.model.model.embed_tokens = MonkeyPatchedEmbedding(original_embed_tokens, pipe.model.device)
```

The problem arises from line 1641 in Qwen2VLForConditionalGeneration for transformers 4.48.0.

```
inputs_embeds = self.model.embed_tokens(input_ids)
```

This is because the device map that accelerate (tried versions 1.2.1 and 0.31.0) that is inferred at line 4164 of transformers modeling_utils.py PreTrainedModel class
```
device_map = infer_auto_device_map(model, dtype=target_dtype, **device_map_kwargs)
```

Says to place the layer `'model.embed_tokens'` onto device 1, which is a problem because the input_ids and attention mask are on device 0.

**Comment by sujunze** [comment]
Thank  @inf3rnus  according to your method the program can run normally.

**Comment by LIU020174** [comment]
@sujunze 想问一下具体在哪里改呀，明白问题在哪里了但是不知道咋解决 T~T

**Comment by sujunze** [comment]
# Monkey patch embedding layer to fix device mismatch
class MonkeyPatchedEmbedding(nn.Module):
    def __init__(self, original_embed_tokens, device):
        super().__init__()
        self.original_embed_tokens = original_embed_tokens
        self.device = device

    def forward(self, *args, **kwargs):
        # Use the original embedding layer but ensure output is on the correct device
        tensors = self.original_embed_tokens(*args, **kwargs)
        return tensors.to(self.device)

# from modelscope import snapshot_download
# model_dir = snapshot_download("qwen/Qwen2-VL-2B-Instruct")
model_dir = "/root/.cache/modelscope/hub/qwen/Qwen2-VL-7B-Instruct"
# default: Load the model on the available device(s)
model = Qwen2VLForConditionalGeneration.from_pretrained(
    model_dir, torch_dtype="auto", device_map="auto"
)
processor = AutoProcessor.from_pretrained(model_dir)
DEBUG = os.getenv('API_DEBUG', 'false').lower() == 'true'
NUM_WORKERS = int(os.getenv('NUM_WORKERS', '1'))
logger = logging.getLogger('uvicorn')

# Patch the embedding layer with the monkey patch
original_embed_tokens = model.model.embed_tokens
model.model.embed_tokens = MonkeyPatchedEmbedding(original_embed_tokens, model.device)****
