### ISSUE TITLE
docker版本启动成功，提交prompt报错

### ISSUE THREAD

**Issue by akfheaven** [QwenLM/Qwen2-VL#613]
root@3a73dd9b73dd:/data/shared/Qwen# python web_demo_mm.py --flash-attn2 --server-name 0.0.0.0
You are attempting to use Flash Attention 2.0 without specifying a torch dtype. This might lead to unexpected behaviour
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 5/5 [04:30<00:00, 54.03s/it]
Some parameters are on the meta device because they were offloaded to the cpu.
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
/usr/local/lib/python3.8/dist-packages/gradio/analytics.py:106: UserWarning: IMPORTANT: You are using gradio version 4.42.0, however version 4.44.1 is available, please upgrade.
--------
  warnings.warn(
User: 你是谁
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1532, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.8/dist-packages/gradio/utils.py", line 671, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.8/dist-packages/gradio/utils.py", line 664, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.8/dist-packages/gradio/utils.py", line 647, in run_sync_iterator_async
    return next(iterator)
  File "/usr/local/lib/python3.8/dist-packages/gradio/utils.py", line 809, in gen_wrapper
    response = next(iterator)
  File "web_demo_mm.py", line 189, in predict
    for response in call_local_model(model, processor, messages):
  File "web_demo_mm.py", line 157, in call_local_model
    for new_text in streamer:
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/streamers.py", line 223, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "/usr/lib/python3.8/queue.py", line 178, in get
    raise Empty
_queue.Empty

**Comment by KLL535** [comment]
I have the same thing. What should I enter in the web demo? Is this a text neural network? I thought it was a neural network that describes pictures, like Florence, where you just throw a picture and it describes it. But here is the Input text field, what should I do with it?

User: test
Traceback (most recent call last):
  File "C:\python2\qwen2\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\python2\qwen2\venv\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\python2\qwen2\venv\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\python2\qwen2\venv\lib\site-packages\gradio\blocks.py", line 1532, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\python2\qwen2\venv\lib\site-packages\gradio\utils.py", line 671, in async_iteration
    return await iterator.__anext__()
  File "C:\python2\qwen2\venv\lib\site-packages\gradio\utils.py", line 664, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\python2\qwen2\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\python2\qwen2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "C:\python2\qwen2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "C:\python2\qwen2\venv\lib\site-packages\gradio\utils.py", line 647, in run_sync_iterator_async
    return next(iterator)
  File "C:\python2\qwen2\venv\lib\site-packages\gradio\utils.py", line 809, in gen_wrapper
    response = next(iterator)
  File "C:\python2\qwen2\web_demo_mm.py", line 189, in predict
    for response in call_local_model(model, processor, messages):
  File "C:\python2\qwen2\web_demo_mm.py", line 157, in call_local_model
    for new_text in streamer:
  File "C:\python2\qwen2\venv\lib\site-packages\transformers\generation\streamers.py", line 224, in __next__
    value = self.text_queue.get(timeout=self.timeout)
  File "queue.py", line 179, in get
_queue.Empty
